library(data.table)
library(tidyverse)


sample_name <- fread("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/list2_gatk", header = F)
sample_name$V1 <- gsub(".vcf", "", sample_name$V1)
llimit <- 10
ulimit <- 250


for (i in 1:nrow(sample_name)) {
  gatk_out <- fread(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/", sample_name[i], "_2.txt"))
  colnames(gatk_out)[c(1, 6, 7)] <- c("CHROM", "Ref_GATK", "Alt_GATK")
  gatk_out <- gatk_out %>% select(-GT)
  gatk_out <- gatk_out %>% filter(CHROM != "MT" & CHROM != "X")
  gatk_out$CHROM <- as.numeric(gatk_out$CHROM)
  rc_g_i <- fread(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/", sample_name[i], "_5.csv"), select = c(1:4, 11, 10, 14))
  colnames(rc_g_i)[5:7] <- c("Ref_rC", "Alt_rC", "VAF_rC")
  mpileup_out <- fread(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/", sample_name[i], "_mpileup_2.txt"))
  colnames(mpileup_out)[1] <- "CHROM"
  mpileup_out <- mpileup_out %>% separate(DP4, into = c("ref-f", "ref-r", "alt-f", "alt-r"))
  mpileup_out <- mpileup_out %>% filter(CHROM != "MT" & CHROM != "X")
  mpileup_out$CHROM <- as.numeric(mpileup_out$CHROM)
  class(mpileup_out$`ref-f`) <- "integer"
  class(mpileup_out$`ref-r`) <- "integer"
  class(mpileup_out$`alt-f`) <- "integer"
  class(mpileup_out$`alt-r`) <- "integer"
  mpileup_out$Ref_mp <- rowSums(mpileup_out[,6:7])
  mpileup_out$Alt_mp <- rowSums(mpileup_out[,8:9])
  mpileup_out <- mpileup_out %>% select(-`ref-f`, -`ref-r`, -`alt-f`, -`alt-r`, -GT)
  colnames(mpileup_out)[1] <- "CHROM"

  anno_snvs <- fread(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/", sample_name[i], "_SNVs.txt"))
  anno_snvs <- anno_snvs %>% dplyr::filter(rsID != 0 & repeatMasker == "none" & tandemRepeat == "none") %>% dplyr::select(chromosome, position, referenceBase, sampleGenotype) %>% distinct()
  colnames(anno_snvs) <- c("CHROM", "POS", "REF", "ALT")
  # anno_snvs2 <- anno_snvs1[duplicated(anno_snvs1),]
  combo <- inner_join(inner_join(inner_join(rc_g_i, gatk_out), mpileup_out), anno_snvs)
  combo <- inner_join(inner_join(rc_g_i, gatk_out), mpileup_out)
  combo$total_GATK <- rowSums(combo[,8:9]) #%>% mutate(VAF_GATK = Alt_GATK/total_GATK)
  combo$VAF_GATK <- combo$Alt_GATK/combo$total_GATK
  combo$total_rC <- rowSums(combo[,5:6])
  combo$total_mp <- rowSums(combo[,10:11]) #%>% mutate(VAF_GATK = Alt_GATK/total_GATK)
  combo$VAF_mp <- combo$Alt_mp/combo$total_mp
  combo <- combo %>% mutate(VAF_diff1 = abs(VAF_rC-VAF_GATK), total_diff1 = (total_rC-total_GATK), ref_diff1 = (Ref_rC-Ref_GATK), alt_diff1 = (Alt_rC-Alt_GATK),
                            VAF_diff2 = abs(VAF_rC-VAF_mp), total_diff2 = (total_rC-total_mp), ref_diff2 = (Ref_rC-Ref_mp), alt_diff2 = (Alt_rC-Alt_mp),
                            VAF_diff3 = abs(VAF_GATK-VAF_mp), total_diff3 = (total_GATK-total_mp), ref_diff3 = (Ref_GATK-Ref_mp), alt_diff3 = (Alt_GATK-Alt_mp))
  # fwrite(combo[,1:4], paste0(sample_name[i], "_SNVs.txt"), sep = "\t", col.names = F)
  combo <- combo[which(total_GATK > llimit & total_GATK < ulimit & total_mp > llimit & total_mp < ulimit),]
  # setorder(combo, total_GATK)

  
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_", sample_name[i], "_VAF_GATK.png"))
  # hist(combo$VAF_diff1, main = paste0(sample_name[i], " (|rC-GATK|)"), xlab = "VAF")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_",sample_name[i], "_total_reads_GATK.png"))
  # hist(combo$total_diff1, main = paste0(sample_name[i], " (rC-GATK)"), xlab = "Reads")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_", sample_name[i], "_Ref_reads_GATK.png"))
  # hist(combo$ref_diff1, main = paste0(sample_name[i], " (rC-GATK)"), xlab = "Reads")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_", sample_name[i], "_Alt_reads_GATK.png"))
  # hist(combo$alt_diff1, main = paste0(sample_name[i], " (rC-GATK)"), xlab = "Reads")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_", sample_name[i], "_VAF_mp.png"))
  # hist(combo$VAF_diff2, main = paste0(sample_name[i], " (|rC-mpileup|)"), xlab = "VAF")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_",sample_name[i], "_total_reads_mp.png"))
  # hist(combo$total_diff2, main = paste0(sample_name[i], " (rC-mpileup)"), xlab = "Reads")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_", sample_name[i], "_Ref_reads_mp.png"))
  # hist(combo$ref_diff2, main = paste0(sample_name[i], " (rC-mpileup)"), xlab = "Reads")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_", sample_name[i], "_Alt_reads_mp.png"))
  # hist(combo$alt_diff2, main = paste0(sample_name[i], " (rC-mpileup)"), xlab = "Reads")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_", sample_name[i], "_VAF_G_m.png"))
  # hist(combo$VAF_diff3, main = paste0(sample_name[i], " (|GATK-mpileup|)"), xlab = "VAF")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_",sample_name[i], "_total_reads_G_m.png"))
  # hist(combo$total_diff3, main = paste0(sample_name[i], " (GATK-mpileup)"), xlab = "Reads")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_", sample_name[i], "_Ref_reads_G_m.png"))
  # hist(combo$ref_diff3, main = paste0(sample_name[i], " (GATK-mpileup)"), xlab = "Reads")
  # dev.off()
  # png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Bulk/hist_", sample_name[i], "_Alt_reads_G_m.png"))
  # hist(combo$alt_diff3, main = paste0(sample_name[i], " (GATK-mpileup)"), xlab = "Reads")
  # dev.off()
  
  
  
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_", sample_name[i], "_VAF_GATK.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$VAF_GATK, combo$VAF_rC,  xlab = "GATK", ylab = "rC v2.2", xlim = c(0, 1), ylim = c(0, 1), cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_",sample_name[i], "_total_reads_GATK.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$total_GATK, combo$total_rC, xlab = "GATK Reads", ylab = "rC v2.2 Reads", cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_", sample_name[i], "_Ref_reads_GATK.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$Ref_GATK, combo$Ref_rC, xlab = "GATK Reads", ylab = "rC v2.2 Reads", cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_", sample_name[i], "_Alt_reads_GATK.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$Alt_GATK, combo$Alt_rC, xlab = "GATK Reads", ylab = "rC v2.2 Reads", cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_", sample_name[i], "_VAF_mp.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$VAF_mp, combo$VAF_rC, xlab = "mpileup", ylab = "rC v2.2", xlim = c(0, 1), ylim = c(0, 1), cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_",sample_name[i], "_total_reads_mp.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$total_mp, combo$total_rC, xlab = "mpileup Reads", ylab = "rC v2.2 Reads", cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_", sample_name[i], "_Ref_reads_mp.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$Ref_mp, combo$Ref_rC, xlab = "mpileup Reads", ylab = "rC v2.2 Reads", cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_", sample_name[i], "_Alt_reads_mp.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$Alt_mp, combo$Alt_rC, xlab = "mpileup Reads", ylab = "rC v2.2 Reads", cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_", sample_name[i], "_VAF_G_m.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$VAF_GATK, combo$VAF_mp, xlab = "GATK", ylab = "mpileup", xlim = c(0, 1), ylim = c(0, 1), cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_",sample_name[i], "_total_reads_G_m.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$total_GATK, combo$total_mp, xlab = "GATK Reads", ylab = "mpileup Reads", cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_", sample_name[i], "_Ref_reads_G_m.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$Ref_GATK, combo$Ref_mp, xlab = "GATK Reads", ylab = "mpileup Reads", cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()
  png(paste0("D:/Virtualbox/Ubuntu/Shared Folder/ReadCounts_subtask/Single_Cell/scatter_", sample_name[i], "_Alt_reads_G_m.png"), width = 560, height = 560)
  par(mar = c(5, 6, 2, 2)+0.1)
  plot(combo$Alt_GATK, combo$Alt_mp, xlab = "GATK Reads", ylab = "mpileup Reads", cex.lab = 2, cex.axis = 1.3)
  abline(a = 0, b = 1, col = "red")
  dev.off()

}
